INSERT INTO STUDENT_GRADES(STUDENT_ID, GRADE_GM, GRADE_INFOR, GRADE_LANG) VALUES ('gpis', 5.0, 5.5, 5.5);
INSERT INTO STUDENT_GRADES(STUDENT_ID, GRADE_GM, GRADE_INFOR, GRADE_LANG) VALUES ('gema', 6.0, 4.0, 5.0);
INSERT INTO STUDENT_GRADES(STUDENT_ID, GRADE_GM, GRADE_INFOR, GRADE_LANG) VALUES ('scep', 3.0, 2.5, 4.0);
INSERT INTO STUDENT_GRADES(STUDENT_ID, GRADE_GM, GRADE_INFOR, GRADE_LANG) VALUES ('heip', 5.0, 3.0, 5.5);