INSERT INTO UNIVERSITY(INSTITUTION, COUNTRY_CODE, ACCREDITATION) VALUES('Hochschule für Technik und Wirtschaft Berlin', 'DE', 'FIBAA');
INSERT INTO UNIVERSITY(INSTITUTION, COUNTRY_CODE, ACCREDITATION) VALUES('San Francisco State University', 'US', 'AACSB');
INSERT INTO UNIVERSITY(INSTITUTION, COUNTRY_CODE, ACCREDITATION) VALUES('Australian Catholic University', 'AU', '');